# Generated by Django 4.2.5 on 2023-12-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rip', '0002_alter_order_end_date_alter_order_in_work_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_for_ship',
            unique_together=set(),
        ),
    ]
